## File generated by the BNF Converter (bnfc 2.9.5).

CC = gcc -g
CCFLAGS = --ansi -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration ${CC_OPTS}

FLEX = flex
FLEX_OPTS = -Pbnfc_grupo_

BISON = bison
BISON_OPTS = -t -pbnfc_grupo_

OBJS = Absyn.o Buffer.o Lexer.o Parser.o Printer.o

.PHONY : clean distclean

all : TestBNFC_grupo

clean :
	rm -f *.o TestBNFC_grupo BNFC_grupo.aux BNFC_grupo.log BNFC_grupo.pdf BNFC_grupo.dvi BNFC_grupo.ps BNFC_grupo

distclean : clean
	rm -f Absyn.h Absyn.c Bison.h Buffer.h Buffer.c BNFC_grupo.l Lexer.c BNFC_grupo.y Parser.h Parser.c Printer.c Printer.h Skeleton.c Skeleton.h Test.c Makefile BNFC_grupo.tex

TestBNFC_grupo : ${OBJS} Test.o
	@echo "Linking TestBNFC_grupo..."
	${CC} ${OBJS} Test.o -o TestBNFC_grupo

Absyn.o : Absyn.c Absyn.h
	${CC} ${CCFLAGS} -c Absyn.c

Buffer.o : Buffer.c Buffer.h
	${CC} ${CCFLAGS} -c Buffer.c

Lexer.c : BNFC_grupo.l
	${FLEX} ${FLEX_OPTS} -oLexer.c BNFC_grupo.l

Parser.c Bison.h : BNFC_grupo.y
	${BISON} ${BISON_OPTS} BNFC_grupo.y -o Parser.c

Lexer.o : CCFLAGS+=-Wno-sign-conversion

Lexer.o : Lexer.c Bison.h
	${CC} ${CCFLAGS} -c Lexer.c

Parser.o : Parser.c Absyn.h Bison.h
	${CC} ${CCFLAGS} -c Parser.c

Printer.o : Printer.c Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Printer.c

Test.o : Test.c Parser.h Printer.h Absyn.h
	${CC} ${CCFLAGS} -c Test.c
